"""cocotb integration testbench for <design_name> — golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (ready, hash_valid, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.

Two verification modes:
- test_layered: Golden model cycle-by-cycle output port comparison (algorithm designs)
- test_internal_signals: Per-cycle internal register comparison against golden model
- test_protocol: Protocol compliance checks (all designs)

Port configuration constants below are populated from design_spec.py by the codegen
stage. If codegen does not populate them, defaults are used and only
top-level port signals are checked.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

# ─── Configurable constants ──────────────────────────────────────────────
# Populated from design_spec.py by the codegen stage.
CLK_PERIOD_NS = 5        # 200 MHz default — override in design_spec.py
TIMEOUT_CYCLES = 500     # Maximum cycles to wait for valid/ready
MAX_SIM_CYCLES = 2000    # Safety limit for comparison loops

# ─── Design spec / golden model import ────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "design_spec.py"
if not GM_PATH.exists():
    GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"  # fallback
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from design_spec import run as golden_run
        GOLDEN_AVAILABLE = True
    except ImportError:
        try:
            from golden_model import run as golden_run  # fallback
            GOLDEN_AVAILABLE = True
        except ImportError:
            pass

# ─── Port configuration ─────────────────────────────────────────────────
# Populated from design_spec.py by the codegen stage.
# Codegen MUST fill these in — they are NOT optional.
# If a port category is empty for this design, codegen sets it to {}.
INPUT_PORTS = {}          # {"port_name": width_bits, ...}
OUTPUT_PORTS = {}         # {"port_name": width_bits, ...}
VALID_OUTPUT_PORTS = []   # ["valid_out", ...] — output ports indicating valid data
HANDSHAKE_PORTS = {}      # {"valid_in": "ready_out"} — valid -> ack mapping
HOLD_UNTIL_ACK_PORTS = [] # ["valid_in", ...] — ports with hold_until_ack protocol

# Number of golden model trace cycles to skip at the start of the comparison.
# With cocotb+iverilog VPI, drive_inputs() consumes 1 RisingEdge that reads
# POST-NBA of the posedge BEFORE the drive. The comparison loop's first
# RisingEdge then reads POST-NBA of the drive posedge, which corresponds to
# golden cycle 1 (IDLE->CALC transition). So DRIVE_PHASE_CYCLES=0 when the
# block_trace already skips golden cycle 0 (reset), or DRIVE_PHASE_CYCLES=1
# when the comparison starts from the full golden trace including cycle 0.
DRIVE_PHASE_CYCLES = 0    # populated by codegen based on design FSM timing


# ─── Signal name mapping ────────────────────────────────────────────────
# Codegen MUST populate this mapping from design_spec.py signal names to DUT
# port names. If left empty, golden model comparison tests will raise an error
# instead of silently passing (false positive prevention).
#
# Example:
#   GOLDEN_TO_PORT = {"ready_reg": "ready", "hash_valid_reg": "hash_valid", ...}
GOLDEN_TO_PORT = {}  # MUST be populated by codegen

# ─── Stimulus injection tracking ──────────────────────────────────────────
# Codegen MUST call mark_stimulus_injected() after calling drive_inputs() in
# test functions. This fail-fast check prevents false positives when codegen
# forgets to add stimulus (all DUT outputs stay at reset values, which may
# coincidentally match golden model trace).
#
# Uses a closure-based approach (instead of module-level mutable global) to
# remain correct even when cocotb runs tests in isolated subprocesses.

def _create_stimulus_tracker():
    """Create a stimulus tracker for a single test function.

    Returns (check, mark) where:
        check()  — raises AssertionError if no stimulus was injected
        mark()   — call after drive_inputs() to record stimulus was driven
    """
    _injected = [False]
    def mark():
        _injected[0] = True
    def check():
        if not _injected[0]:
            raise AssertionError(
                "No stimulus was driven to DUT — codegen MUST call "
                "drive_inputs() and mark_stimulus_injected() before "
                "the comparison loop. All DUT outputs are at reset values."
            )
    return check, mark

# ─── DSL auto-configuration ──────────────────────────────────────────────
# If design_spec.py defines build_*() functions using the VeriFlow DSL,
# extract timing contract to auto-populate GOLDEN_TO_PORT and port config.
# This replaces manual codegen population — the DSL module knows its timing.
# NOTE: This block MUST appear AFTER the port configuration defaults above,
# so it can override empty defaults with DSL-derived values.
_DSL_MODULE = None
if GOLDEN_AVAILABLE and GM_PATH.exists():
    try:
        import importlib.util
        _spec = importlib.util.spec_from_file_location("_ds", str(GM_PATH))
        _mod = importlib.util.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        # Find build_* functions
        _builder_fn = None
        for _attr_name in dir(_mod):
            if _attr_name.startswith("build_") and callable(getattr(_mod, _attr_name)):
                _builder_fn = getattr(_mod, _attr_name)
                break
        if _builder_fn is not None:
            from dsl import VerilogEmitter
            _DSL_MODULE = _builder_fn()
            _contract = VerilogEmitter().emit_timing_contract(_DSL_MODULE)
            # Auto-populate port configuration from DSL timing contract
            if not GOLDEN_TO_PORT:
                GOLDEN_TO_PORT = _contract.get("golden_to_port", {})
            if not OUTPUT_PORTS:
                OUTPUT_PORTS = _contract.get("port_widths", {})
            if not INPUT_PORTS:
                INPUT_PORTS = _contract.get("input_ports", {})
    except ImportError as _dsl_err:
        import warnings
        warnings.warn(
            f"[DSL] VeriFlow DSL module not available: {_dsl_err}. "
            f"Using codegen-populated port configuration.",
            stacklevel=2,
        )
    except Exception as _dsl_err:
        import warnings
        warnings.warn(
            f"[DSL] Auto-configuration failed: {_dsl_err!r}. "
            f"Using codegen-populated port configuration.",
            stacklevel=2,
        )


def _validate_port_config(dut) -> list[str]:
    """Validate port configuration is properly set by codegen.

    Returns list of warning/error messages.
    """
    warnings = []

    if GOLDEN_AVAILABLE and not GOLDEN_TO_PORT:
        warnings.append(
            "[CONFIG] GOLDEN_TO_PORT is empty — golden model comparison tests "
            "will have no signals to compare. Codegen MUST populate this mapping."
        )

    if GOLDEN_AVAILABLE and not OUTPUT_PORTS and not VALID_OUTPUT_PORTS:
        warnings.append(
            "[CONFIG] OUTPUT_PORTS and VALID_OUTPUT_PORTS are both empty — "
            "no output signals configured for verification."
        )

    return warnings


def _check_alignment(expected_cycles, dut_samples, cycle_offset=0, min_check_cycles=4):
    """Verify golden-to-RTL cycle alignment before the full comparison loop.

    Compares the first *min_check_cycles* golden entries against RTL samples.
    If ALL sampled values mismatch (highly unlikely for a true logic bug),
    the alignment offset (DRIVE_PHASE_CYCLES or golden cycle skip) is likely
    wrong. Returns (is_aligned, detail_string).
    """
    compare_start = 1 + cycle_offset  # skip reset cycle + offset
    available = min(len(expected_cycles) - compare_start, len(dut_samples), min_check_cycles)

    if available < 2:
        return True, ""  # not enough data to check

    total_checks = 0
    total_matches = 0

    for i in range(available):
        expected = expected_cycles[compare_start + i]
        sample = dut_samples[i]
        for sig_name, expected_val in expected.items():
            if sig_name in sample:
                total_checks += 1
                if sample[sig_name] == expected_val:
                    total_matches += 1

    if total_checks == 0:
        return True, ""

    match_rate = total_matches / total_checks

    if match_rate == 0:
        return False, (
            f"[ALIGN] ZERO matches in first {available} cycles "
            f"({total_checks} signal checks). "
            f"DRIVE_PHASE_CYCLES={cycle_offset} is likely wrong — "
            f"golden and RTL traces are misaligned. "
            f"Check the offset and re-run."
        )
    elif match_rate < 0.3:
        return False, (
            f"[ALIGN] Low match rate {match_rate:.0%} in first {available} cycles "
            f"({total_matches}/{total_checks}). "
            f"Possible partial alignment issue — verify DRIVE_PHASE_CYCLES={cycle_offset}."
        )

    return True, ""


# ─── Clock management ───────────────────────────────────────────────────
# CRITICAL: In cocotb v2.0+, background tasks (including Clock) are killed
# between tests. Each test MUST call ensure_clock() to start a fresh clock.

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Test result tracking ──────────────────────────────────────────────
# Per-test failure tracking (avoids global state issues with cocotb v2.0+).
# Each test uses its own local counter; test_summary reads all test results.

def _make_fail_counter():
    """Create a per-test fail counter with increment and check methods."""
    count = 0

    class FailCounter:
        def inc(self):
            nonlocal count
            count += 1

        @property
        def value(self):
            return count

        @property
        def has_failures(self):
            return count > 0

    return FailCounter()


# ─── Helpers ────────────────────────────────────────────────────────────

async def reset_dut(dut, fail_counter=None):
    """Apply synchronous reset and wait for outputs to settle."""
    dut.rst.value = 1
    # Zero all input ports only (not outputs — outputs are driven by DUT)
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    # Also zero any valid input ports from HANDSHAKE_PORTS
    for valid_name in HANDSHAKE_PORTS:
        try:
            getattr(dut, valid_name).value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst.value = 0
    await RisingEdge(dut.clk)  # rst deassert sampled, outputs stable


def check(dut, expected, signal, test_name, cycle, fail_counter=None):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    actual = int(signal.value)
    if expected != actual:
        if fail_counter:
            fail_counter.inc()
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


async def drive_inputs(dut, input_values, valid_name='valid_in',
                       ready_name='ready_out'):
    """Wait for ready, then drive valid=1 with input values.

    Timing (POST-NBA):
    1. Wait for ready=1
    2. Drive ALL inputs simultaneously (valid + data)
    3. Wait ONE RisingEdge — DUT samples inputs at this posedge, NBA fires
    4. Deassert inputs (for single_cycle) or hold (for hold_until_ack)

    After this function returns, the DUT has consumed the inputs and its
    registered state reflects the transition (e.g., loaded data, FSM advance).
    The caller should account for this consumed cycle when aligning the
    golden model trace for comparison (see DRIVE_PHASE_CYCLES).

    IMPORTANT limitations:
      - Assumes a simple valid/ready handshake (ready HIGH before valid asserted).
      - Does NOT handle pipeline handshake (ready may drop after valid asserted).
      - Does NOT handle backpressure (ready cycling low during processing).
      - For backpressure designs, write a custom drive function that polls
        ready continuously and holds valid high until the DUT accepts.

    Args:
        dut: cocotb DUT handle
        input_values: dict mapping port names to integer values
        valid_name: name of the valid input port
        ready_name: name of the ready/ack output port
    """
    # Wait for ready
    timeout = TIMEOUT_CYCLES
    ready_sig = getattr(dut, ready_name)
    while int(ready_sig.value) != 1 and timeout > 0:
        await RisingEdge(dut.clk)
        timeout -= 1
    assert timeout > 0, "Timeout waiting for ready before drive_inputs"

    # Drive all inputs at once
    for port_name, value in input_values.items():
        getattr(dut, port_name).value = value
    getattr(dut, valid_name).value = 1

    # Wait one rising edge — DUT samples inputs at this posedge
    await RisingEdge(dut.clk)

    # Deassert based on handshake protocol
    if valid_name in HOLD_UNTIL_ACK_PORTS:
        # hold_until_ack: keep valid high until DUT asserts ready
        # (ready was already high when we started, so DUT has sampled.
        #  But for multi-cycle holds, wait for ready to be asserted again)
        pass  # caller is responsible for deasserting after ack
    else:
        # single_cycle / pulse: deassert after DUT has sampled
        getattr(dut, valid_name).value = 0
        for port_name in input_values:
            getattr(dut, port_name).value = 0


async def wait_valid(dut, valid_name='valid_out', max_cycles=None):
    """Poll for valid=1, return cycle count waited."""
    if max_cycles is None:
        max_cycles = TIMEOUT_CYCLES
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1  # timeout


# ─── Multi-block NBA-aware wait pattern ─────────────────────────────────
# IMPORTANT: When sending multiple blocks to a DUT with FSM (IDLE→CALC→DONE→IDLE),
# you MUST account for NBA propagation after driving each block.
#
# At RisingEdge N, cocotb reads POST-NBA of posedge N-1.
# After drive_inputs(), the DUT transitions state at the NEXT posedge.
# You must wait at least ONE RisingEdge for the NBA to propagate before
# polling ready/state signals.
#
# WRONG (reads stale ready=1 from previous IDLE state):
#   drive_inputs(dut, ...)
#   while int(dut.ready.value) != 1:   # stale! DUT still in IDLE at this point
#       await RisingEdge(dut.clk)
#
# CORRECT:
#   drive_inputs(dut, ...)
#   await RisingEdge(dut.clk)          # let NBA propagate: IDLE → CALC
#   while int(dut.ready.value) != 1:   # now reads post-NBA CALC state
#       await RisingEdge(dut.clk)
#
# This pattern applies to ANY multi-block/multi-operation test where the DUT
# goes through state transitions between operations.


# ─── VCD capture for cocotb ────────────────────────────────────────────
# cocotb + iverilog does not automatically produce VCD. Enable it
# so that vcd2table.py can analyze waveforms after simulation.
def enable_vcd(dut, design_name="dut"):
    """Enable VCD dump for waveform analysis."""
    try:
        dut._log.info(f"[VCD] Enabling waveform capture for {design_name}")
        # cocotb passes PLUSARGS to iverilog — use $dumpfile/$dumpvars
        # via the Verilog testbench wrapper or force VCD via command line.
        # NOTE: For cocotb, VCD must be enabled via iverilog compile flags
        # or by including a Verilog wrapper with $dumpfile/$dumpvars.
        # The cocotb_runner.py handles this via build_args.
    except Exception:
        pass


# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    fc = _make_fail_counter()
    await ensure_clock(dut)
    await reset_dut(dut)

    # Validate config
    for w in _validate_port_config(dut):
        dut._log.warning(w)

    # After reset: verify all valid output ports are 0
    reset_ok = True
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                fc.inc()
                dut._log.error(f"[RESET] {valid_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {valid_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance — handshake and valid behavior.

    Checks that apply to ALL designs regardless of golden model availability:
    1. Reset clears all valid output ports
    2. hold_until_ack: valid stays high until ack received
    3. single_cycle: valid is high for exactly one cycle
    4. No stale valid after operation completes

    Note: Checks 2-4 require stimulus. Codegen adds design-specific
    protocol monitors. This test provides the framework.
    """
    fc = _make_fail_counter()
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check 1: After reset, all valid output ports must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                fc.inc()
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass  # port not found in DUT, skip

    # Check 2-4: Design-specific protocol monitors added by codegen
    # Example for hold_until_ack monitoring:
    #   prev_valid = 0
    #   for cycle in range(MAX_SIM_CYCLES):
    #       await RisingEdge(dut.clk)
    #       cur_valid = int(dut.valid_out.value)
    #       cur_ready = int(dut.ready_out.value)
    #       if prev_valid == 1 and cur_valid == 0 and cur_ready == 0:
    #           dut._log.error("[PROTOCOL] valid dropped before ready")
    #       prev_valid = cur_valid

    if not fc.has_failures:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification — golden model cycle-by-cycle comparison.

    For algorithm designs with a golden model:
    1. Drive input stimulus from golden model test vectors
    2. Compare DUT output signals against golden model per-cycle expected values
    3. Fail-fast on first mismatch: report cycle, signal, expected vs actual
    4. This quickly isolates WHERE the first computation error occurs

    Skipped if design_spec.py (or golden_model.py) is not available.
    """
    fc = _make_fail_counter()

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: design_spec.py not available")
        return

    # Validate GOLDEN_TO_PORT is populated (prevent false positive)
    if not GOLDEN_TO_PORT:
        dut._log.error(
            "[LAYERED] GOLDEN_TO_PORT is empty — no signal mapping configured. "
            "Codegen MUST populate GOLDEN_TO_PORT from design_spec.py. "
            "Aborting test to prevent false positive."
        )
        fc.inc()
        raise AssertionError(
            "test_layered: GOLDEN_TO_PORT is empty — cannot compare signals. "
            "Codegen must populate this mapping."
        )

    await ensure_clock(dut)
    await reset_dut(dut)

    # Validate config
    for w in _validate_port_config(dut):
        dut._log.warning(w)

    # Stimulus tracker — codegen MUST call mark() after drive_inputs()
    _check_stimulus, _mark_stimulus = _create_stimulus_tracker()
    # <CODEGEN: call _mark_stimulus() after drive_inputs()>

    # Fail-fast: if DUT has input ports and golden model is available,
    # stimulus MUST have been injected by codegen. Otherwise all DUT outputs
    # are just reset/initial values and comparison is meaningless.
    if GOLDEN_AVAILABLE and INPUT_PORTS:
        _check_stimulus()

    # NOTE: codegen replaces this comment with actual drive_inputs() calls
    # followed by _mark_stimulus(). If no drive_inputs() is added, the
    # _check_stimulus() call above will raise AssertionError.

    # Get golden model expected values
    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_layered: golden model returned no data")
        return

    dut._log.info(f"[LAYERED] Comparing {len(expected_cycles)} cycles against golden model")

    # IMPORTANT: codegen MUST add drive_inputs() call here with golden model
    # test vectors before the comparison loop. Without driving inputs,
    # the DUT has no stimulus and all outputs will be initial values.
    #
    # Example (codegen fills in):
    #   test_vectors = design_spec.TEST_VECTORS
    #   for vec in test_vectors:
    #       await drive_inputs(dut, vec["inputs"], valid_name="valid_in",
    #                         ready_name="ready_out")
    #
    # If design_spec.py provides input data per cycle, drive it here.
    # If the design processes a single input block, drive once then wait.

    first_divergence = None
    cycles_checked = 0
    alignment_checked = False
    # Collect first few RTL samples for alignment verification
    _alignment_samples = []

    # Skip golden cycle 0 (reset state) + DRIVE_PHASE_CYCLES offset.
    compare_cycles = expected_cycles[1 + DRIVE_PHASE_CYCLES:]

    for cycle_idx, expected in enumerate(compare_cycles):
        if cycle_idx >= MAX_SIM_CYCLES:
            dut._log.warning(f"[LAYERED] Hit MAX_SIM_CYCLES={MAX_SIM_CYCLES} limit, stopping")
            break

        # Wait one cycle for DUT to produce output
        await RisingEdge(dut.clk)

        # Compare each output signal against golden model
        for sig_name, expected_val in expected.items():
            # Map golden trace name to DUT port name
            dut_name = GOLDEN_TO_PORT.get(sig_name)
            if dut_name is None:
                continue  # not a mapped output port
            try:
                sig = getattr(dut, dut_name)
                actual_val = int(sig.value)
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": cycle_idx,
                        "signal": sig_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except AttributeError:
                pass  # signal not accessible in DUT hierarchy, skip

        # Collect sample for alignment verification
        if not alignment_checked:
            sample = {}
            for sig_name in expected:
                dut_name = GOLDEN_TO_PORT.get(sig_name)
                if dut_name:
                    try:
                        sample[dut_name] = int(getattr(dut, dut_name).value)
                    except AttributeError:
                        pass
            _alignment_samples.append(sample)

        cycles_checked += 1

        # Check alignment after collecting enough samples
        if not alignment_checked and len(_alignment_samples) >= 6:
            aligned, msg = _check_alignment(
                expected_cycles, _alignment_samples, DRIVE_PHASE_CYCLES
            )
            if not aligned:
                dut._log.error(msg)
            alignment_checked = True

        if first_divergence:
            break

    # Report results
    if first_divergence:
        fc.inc()
        div = first_divergence
        # Classify the error type for guided diagnosis
        if div["actual"] == 0 and div["expected"] != 0:
            bug_type = "A (computation=0, expected non-zero → logic error or missing init)"
        else:
            diff = div["actual"] ^ div["expected"]
            bug_type = f"A (data-wrong, xor_diff=0x{diff:x} → logic or init error)"

        msg = (
            f"[LAYERED] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x} "
            f"→ bug_type={bug_type}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[LAYERED] PASS — {cycles_checked} cycles matched golden model"
        )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    This is the KEY verification test. It reads RTL internal registers
    via VPI (cocotb's dut.hierarchy.signal.value) and compares them
    against golden model trace on EVERY clock cycle.

    This test catches bugs that test_layered misses — test_layered only
    compares top-level output ports, missing internal register divergences.

    Timing semantics:
        After `await RisingEdge(dut.clk)`, cocotb + iverilog VPI reads values
        produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
        cocotb sees POST-NBA of posedge N-1.

        The golden model trace records POST-NBA state for each posedge.
        The comparison loop reads trace[N] at RisingEdge N, which shows the
        results of posedge N-1's computation.

        Registered outputs (ready, valid, etc.) have a 1-cycle delay from
        the FSM state that computes them — the golden model must track this.

    Skipped if design_spec.py trace mode does not include internal signals.
    """
    fc = _make_fail_counter()

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: design_spec.py not available")
        return

    # Validate GOLDEN_TO_PORT or internal signal access
    if not GOLDEN_TO_PORT:
        # For internal signals, GOLDEN_TO_PORT may not be populated since
        # signals are accessed directly. But we warn anyway.
        dut._log.warning(
            "[INTERNAL] GOLDEN_TO_PORT is empty — codegen should populate "
            "this for output port comparison."
        )

    await ensure_clock(dut)
    await reset_dut(dut)

    # Validate config
    for w in _validate_port_config(dut):
        dut._log.warning(w)

    # Stimulus tracker — codegen MUST call mark() after drive_inputs()
    _check_stimulus, _mark_stimulus = _create_stimulus_tracker()
    # <CODEGEN: call _mark_stimulus() after drive_inputs()>

    # Fail-fast: stimulus check (same as test_layered)
    if GOLDEN_AVAILABLE and INPUT_PORTS:
        _check_stimulus()

    # NOTE: codegen replaces this comment with actual drive_inputs() calls
    # followed by _mark_stimulus().

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    # Check if trace includes internal signals (any key containing '.' or ending with _reg)
    has_internal = any('.' in k or k.endswith('_reg')
                       for entry in expected_cycles for k in entry.keys())
    if not has_internal:
        dut._log.info("[SKIP] test_internal_signals: golden trace has no internal signals")
        return

    dut._log.info(f"[INTERNAL] Comparing {len(expected_cycles)} cycles, internal signals")

    # IMPORTANT: codegen MUST add drive_inputs() call here with golden model
    # test vectors before the comparison loop. Without driving inputs,
    # the DUT has no stimulus and all outputs will be initial values.
    # <CODEGEN: drive_inputs() call here — same as test_layered>

    first_divergence = None
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []
    alignment_checked = False
    _alignment_samples = []

    # Align golden trace with DUT state after drive phase.
    # Skip golden cycle 0 (reset state) + DRIVE_PHASE_CYCLES offset, same as test_layered.
    compare_cycles = expected_cycles[1 + DRIVE_PHASE_CYCLES:]

    for cycle_idx, expected in enumerate(compare_cycles):
        if cycle_idx >= MAX_SIM_CYCLES:
            dut._log.warning(f"[INTERNAL] Hit MAX_SIM_CYCLES={MAX_SIM_CYCLES} limit, stopping")
            break

        await RisingEdge(dut.clk)

        for sig_name, expected_val in expected.items():
            if sig_name in INPUT_PORTS:
                continue  # skip input signals

            try:
                # Navigate VPI hierarchy for module-qualified names
                if '.' in sig_name:
                    parts = sig_name.split('.')
                    obj = dut
                    for part in parts:
                        # Handle array indexing: w_reg[0] → w_reg, index 0
                        if '[' in part:
                            arr_name, idx_str = part.split('[')
                            idx = int(idx_str.rstrip(']'))
                            obj = getattr(obj, arr_name)
                            obj = obj[idx]
                        else:
                            obj = getattr(obj, part)
                    actual_val = int(obj.value)
                else:
                    sig = getattr(dut, sig_name)
                    actual_val = int(sig.value)

                signals_compared += 1
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": cycle_idx,
                        "signal": sig_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        cycles_checked += 1

        # Collect sample for alignment verification (use mapped output ports)
        if not alignment_checked:
            sample = {}
            for sig_name in expected:
                dut_name = GOLDEN_TO_PORT.get(sig_name, sig_name)
                try:
                    sample[dut_name] = int(getattr(dut, dut_name).value)
                except (AttributeError, IndexError):
                    pass
            _alignment_samples.append(sample)

        if not alignment_checked and len(_alignment_samples) >= 6:
            aligned, msg = _check_alignment(
                expected_cycles, _alignment_samples, DRIVE_PHASE_CYCLES
            )
            if not aligned:
                dut._log.error(msg)
            alignment_checked = True

        if first_divergence:
            break

    # Warn about signals that could not be found in DUT hierarchy
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (f" ... and {len(signals_not_found)-5} more" if len(signals_not_found) > 5 else "")
        )

    # Safety check: verify we actually compared something
    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared — golden trace signal names "
            "do not match any DUT signals. Check naming convention."
        )
        fc.inc()
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if first_divergence:
        fc.inc()
        div = first_divergence
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS — {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    Collects results from all previous tests by checking for any
    test failures reported via cocotb's test result mechanism.
    """
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    # cocotb tracks per-test pass/fail automatically via AssertionError.
    # If we reach here, all tests that didn't raise errors passed.
    dut._log.info("ALL TESTS PASSED")
