#!/usr/bin/env python3
"""Wave 3 helper: extract constants, inject S8, merge parts, validate.

Usage: python merge_design_spec.py <project_dir>

Eliminates all shell quoting/escaping issues by doing everything in Python.
"""

import importlib.util
import inspect
import os
import re
import sys
from pathlib import Path


def extract_constants(parts_dir: Path, output_path: Path) -> None:
    """Step 1: Execute all zero-arg print_*_verilog() functions and save output."""
    s3_path = parts_dir / "s3_constants.py"
    if not s3_path.exists():
        print("[WARN] s3_constants.py not found, skipping constant extraction")
        return

    spec = importlib.util.spec_from_file_location("s3_constants", str(s3_path))
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(parts_dir))
    spec.loader.exec_module(mod)

    with open(output_path, "w", encoding="utf-8") as f:
        for name, obj in inspect.getmembers(mod, inspect.isfunction):
            if name.startswith("print_") and name.endswith("_verilog"):
                sig = inspect.signature(obj)
                try:
                    if len(sig.parameters) == 0:
                        result = obj()
                    else:
                        # Skip generic helpers that need arguments
                        continue
                except Exception as e:
                    print(f"[WARN] {name}() failed: {e}")
                    continue
                f.write(f"// === Extracted from design_spec.py: {name}() ===\n")
                f.write(result)
                f.write("\n\n")

    print("[OK] Constant extraction complete")


def inject_s8(parts_dir: Path) -> None:
    """Step 2: Write S8 scaffold file."""
    scaffold = r'''# ============================================================
# Section 8: Standard Interface (AUTO-INJECTED SCAFFOLD)
# ============================================================
# This section is auto-generated by the pipeline merge step.
# DO NOT edit manually -- changes will be overwritten.

def run(test_vector_index: int = 0) -> list[dict]:
    """Run a test vector and return cycle-accurate expected values.

    Consumed by:
      - vcd2table.py (import run(), get list[dict])
      - cocotb testbench (per-cycle comparison)
      - Verilog TB generation (extract expected final outputs)
    """
    tv = TEST_VECTORS[test_vector_index]
    return compute(tv["inputs"], trace=True)


def get_test_vectors() -> list[dict]:
    """Return test vectors with final expected outputs (for testbench generation)."""
    results = []
    for tv in TEST_VECTORS:
        computed = compute(tv["inputs"], trace=False)
        results.append({
            "name": tv["name"],
            "inputs": tv["inputs"],
            "expected": tv.get("expected") or computed,
        })
    return results


if __name__ == "__main__":
    import sys

    # === Interface Contract Validation (auto-injected, DO NOT EDIT) ===
    print("=== Interface Contract Validation ===")
    _contract_ok = True

    # Check compute() signature
    import inspect
    _sig = inspect.signature(compute)
    _params = list(_sig.parameters.keys())
    if _params != ["inputs", "trace"]:
        print(f"[FATAL] compute() signature mismatch: {_params} != ['inputs', 'trace']")
        _contract_ok = False

    # Check run() signature
    _sig_run = inspect.signature(run)
    _params_run = list(_sig_run.parameters.keys())
    if _params_run != ["test_vector_index"]:
        print(f"[FATAL] run() signature mismatch: {_params_run} != ['test_vector_index']")
        _contract_ok = False

    # Check get_test_vectors() signature
    _sig_gtv = inspect.signature(get_test_vectors)
    _params_gtv = list(_sig_gtv.parameters.keys())
    if _params_gtv != []:
        print(f"[FATAL] get_test_vectors() signature mismatch: {_params_gtv} != []")
        _contract_ok = False

    # Functional smoke: compute must accept dict input
    try:
        _tv0 = TEST_VECTORS[0]
        _r = compute(_tv0["inputs"], trace=False)
        if not isinstance(_r, dict):
            print(f"[FATAL] compute(trace=False) must return dict, got {type(_r).__name__}")
            _contract_ok = False
    except Exception as _e:
        print(f"[FATAL] compute() smoke test failed: {_e}")
        _contract_ok = False

    if _contract_ok:
        print("[PASS] Interface contract OK")
    else:
        sys.exit(1)

    # Run cycle trace for vcd2table
    print("\n=== Design Spec: cycle trace ===")
    cycles = run(0)
    for i, entry in enumerate(cycles):
        parts = []
        for k in sorted(entry.keys()):
            v = entry[k]
            if isinstance(v, int) and v > 0xFFFF:
                parts.append(f"{k}=0x{v:08x}")
            else:
                parts.append(f"{k}={v}")
        print(f"cycle {i}: {' '.join(parts)}")

    # Verify all test vectors
    print("\n=== Verification ===")
    all_pass = True
    for tv in get_test_vectors():
        computed = compute(tv["inputs"], trace=False)
        ok = computed == tv["expected"]
        all_pass = all_pass and ok
        # Auto-detect primary output field (first non-input key)
        _out_keys = [k for k in computed.keys()]
        _primary = _out_keys[0] if _out_keys else "output"
        _val = tv["expected"].get(_primary, 0)
        if isinstance(_val, int) and _val > 0xFFFF:
            print(f"[{'PASS' if ok else 'FAIL'}] {tv['name']}: {_primary}=0x{_val:08x}")
        else:
            print(f"[{'PASS' if ok else 'FAIL'}] {tv['name']}: {_primary}={_val}")
        if not ok:
            print(f"  expected: {tv['expected']}")
            print(f"  computed: {computed}")

    sys.exit(0 if all_pass else 1)
'''
    s8_path = parts_dir / "s8_interface.py"
    s8_path.write_text(scaffold, encoding="utf-8")
    print("[OK] S8 scaffold injected")


def strip_future_imports(content: str) -> str:
    """Remove 'from __future__ import ...' lines from content."""
    return re.sub(r'^from __future__ import .*\n?', '', content, flags=re.MULTILINE)


def strip_cross_module_imports(content: str) -> str:
    """Remove 'from workspace.docs._parts import ...' lines from content."""
    return re.sub(r'^from workspace\.docs\._parts import .*\n?', '', content, flags=re.MULTILINE)


def merge(parts_dir: Path, output_path: Path) -> None:
    """Step 3: Merge all parts into final design_spec.py."""
    header = '"""design_spec.py -- Python Design Specification.\n\nGenerated by VeriFlow Stage 1 (optimized).\n"""\n\n'
    parts_order = [
        "s1_interface", "s2_hierarchy", "s3_constants",
        "s4_helpers", "s5_pseudocode", "s7_test_vectors",
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

        # Sections 1-5 and 7, with cleanup
        for part in parts_order:
            path = parts_dir / (part + ".py")
            if not path.is_file():
                print(f"[FATAL] Missing part: {path}")
                sys.exit(1)
            content = path.read_text(encoding="utf-8")
            # Strip problematic imports that don't work in merged file
            content = strip_future_imports(content)
            content = strip_cross_module_imports(content)
            f.write(content)
            f.write("\n\n")

        # Section 6: compute() with scaffold wrapper + agent body
        compute_path = parts_dir / "s6_compute_body.py"
        if not compute_path.is_file():
            print(f"[FATAL] Missing part: {compute_path}")
            sys.exit(1)

        compute_body = compute_path.read_text(encoding="utf-8")
        compute_body = strip_future_imports(compute_body)
        compute_body = strip_cross_module_imports(compute_body)

        f.write("# ============================================================\n")
        f.write("# Section 6: Top-Level Integration\n")
        f.write("# ============================================================\n\n")
        f.write("def compute(inputs: dict, trace: bool = False) -> dict | list[dict]:\n")
        f.write('    """Execute the design cycle-accurately.\n\n')
        f.write('    Args:\n')
        f.write('        inputs: {"blocks": [int, ...], "is_last_flags": [bool, ...]}\n')
        f.write('        trace:  False -> dict of final outputs\n')
        f.write('                True  -> list[dict] per cycle for cocotb comparison\n')
        f.write('    """\n')
        for line in compute_body.splitlines():
            if line.strip():
                f.write("    " + line + "\n")
            else:
                f.write("\n")
        f.write("\n\n")

        # Section 8: auto-injected scaffold
        s8_path = parts_dir / "s8_interface.py"
        if not s8_path.is_file():
            print(f"[FATAL] Missing part: {s8_path}")
            sys.exit(1)
        f.write(s8_path.read_text(encoding="utf-8"))

    print(f"[OK] Merged into {output_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python merge_design_spec.py <project_dir>", file=sys.stderr)
        sys.exit(1)

    project_dir = Path(sys.argv[1]).resolve()
    parts_dir = project_dir / "workspace" / "docs" / "_parts"
    output_path = project_dir / "workspace" / "docs" / "design_spec.py"
    constants_path = project_dir / "workspace" / "docs" / "_extracted_constants.v"

    print(f"[INFO] Project: {project_dir}")
    print(f"[INFO] Parts:   {parts_dir}")

    extract_constants(parts_dir, constants_path)
    inject_s8(parts_dir)
    merge(parts_dir, output_path)

    print("[OK] Wave 3 complete")


if __name__ == "__main__":
    main()
